server:
  port: 8020
logging:
  level:
    com.cq: debug
  file:
    path: H:/hh
#    激活配置文件
#spring:
#  profiles:
#    active: dev

person:
  name: zhangsan
  age: 16
  map: {lilei: ss,zhaowu: zz}
  list:
    - 张飞
    - 赵云
  dog:
    name: 小黑
    age: 2

---
profiles: dev

server:
  port: 8083
---
server:
     port: 8084
spring:
  profiles: prod
